<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Warning_ctl00ctl00PCMCbtnUpload</name>
   <tag></tag>
   <elementGuidId>df91d8ce-2c03-40c1-8ba6-eb58303601a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PC_MC_btnUpload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PC_MC_btnUpload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Upload&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a8fa9d8-c2c0-48f5-ad3e-d16d8c1fa2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ed995cc5-92dd-4875-8d11-95ed02d8d5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$PC$MC$btnUpload</value>
      <webElementGuid>15a50859-6264-4899-9c81-811b5f2a2d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>ba873b3e-101f-4af2-a186-4fcb3fffdb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ctl00$PC$MC$btnUpload&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>fadc8aab-a524-4317-9bf0-149e905bb539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PC_MC_btnUpload</value>
      <webElementGuid>1d8ebc59-5d0c-411a-88ec-390011358d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1901</value>
      <webElementGuid>f115543f-b01b-403e-91cb-958c1f011974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>genbutton upload</value>
      <webElementGuid>0fda7b12-100d-4203-9c0e-5df1dfd7dbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PC_MC_btnUpload&quot;)</value>
      <webElementGuid>2d17326e-93d7-4628-bca4-e5dc1c0d38d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PC_MC_btnUpload']</value>
      <webElementGuid>697b945a-2e90-4e43-af02-32a5ea425007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PC_MC_UpdatePanel1']/div/input</value>
      <webElementGuid>90196f09-a358-4e57-8606-37a02a4a3576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>77e8f05f-c87b-49bd-a7bd-5ac49e6edb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ctl00$PC$MC$btnUpload' and @id = 'PC_MC_btnUpload']</value>
      <webElementGuid>7b63f9b3-886a-4997-a789-d5e7a0e2dd14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
