<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cashflow Type_ctl00ctl00PCMCbtnUpload</name>
   <tag></tag>
   <elementGuidId>53107f4b-ca25-4856-86a5-2fe53007701a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PC_MC_btnUpload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PC_MC_btnUpload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Upload New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6f95708-6320-4e1f-a358-2e4bf0e6daf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>979dbc62-cc47-4cbc-b75d-fd5ea013d96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$PC$MC$btnUpload</value>
      <webElementGuid>fd36acb1-da09-4383-9551-bd4c25aa3375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Upload New</value>
      <webElementGuid>eb60300b-bc83-4c8c-ac53-9372f9be8199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PC_MC_btnUpload</value>
      <webElementGuid>c5709734-99a0-4a32-a9df-78a9390c744c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1004</value>
      <webElementGuid>916fee2f-d3c1-4518-8a0b-b5620721732a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>genbutton upload</value>
      <webElementGuid>d113a09b-6444-4f1c-8d14-216cd00aa6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PC_MC_btnUpload&quot;)</value>
      <webElementGuid>77a69910-f957-4f76-9ea5-039bf1b827ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PC_MC_btnUpload']</value>
      <webElementGuid>4e1c61df-fa7f-4008-92f1-367456e937ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/div[3]/div[3]/div/input</value>
      <webElementGuid>a1f1f89e-4e9a-48d9-a9f9-2b0124cc15e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8cbb77e6-58f6-480a-95fd-9e2139d4fde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ctl00$PC$MC$btnUpload' and @id = 'PC_MC_btnUpload']</value>
      <webElementGuid>e87304f0-25d8-40f6-9d36-1f6f541562fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
