<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cashflow Type_ctl00ctl00PCMCbtnDownload</name>
   <tag></tag>
   <elementGuidId>30083b29-270b-4845-9717-155328c533e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PC_MC_btnDownload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PC_MC_btnDownload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Download Format&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9deb0b9e-d293-44fb-9ccb-f68ef7c0baaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9a977de7-3def-4739-a4e1-c65fc7bd800b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$PC$MC$btnDownload</value>
      <webElementGuid>e52b6377-c8c0-44e3-8cc4-fdaef374ddca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Download Format</value>
      <webElementGuid>ea9a0d25-f0a8-4141-b04d-09ba3ad52700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PC_MC_btnDownload</value>
      <webElementGuid>5fd00ffe-fffc-4800-8bbb-e8d87c5f4567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1005</value>
      <webElementGuid>f685aade-ef6e-4b26-96a0-703be57ade9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>genbutton download</value>
      <webElementGuid>c5a0957e-0fae-4f86-b938-e206e0ef08b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PC_MC_btnDownload&quot;)</value>
      <webElementGuid>9b5e6dca-f5fd-4a4f-8afc-d5d345ef594a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PC_MC_btnDownload']</value>
      <webElementGuid>90bb1f5b-73ad-4d8f-899f-fa67c411c33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/div[3]/div[3]/div/input[2]</value>
      <webElementGuid>4aca85be-f266-452c-adce-eb7a5a894a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[2]</value>
      <webElementGuid>7dc8d28d-2855-4a81-8e66-a696b614ebc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ctl00$PC$MC$btnDownload' and @id = 'PC_MC_btnDownload']</value>
      <webElementGuid>e60350c3-b913-49d9-a9f6-39eafc66c2cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
