<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invalid input,Please enter 6 digits_c_da073e</name>
   <tag></tag>
   <elementGuidId>67f89347-1931-41e6-b4aa-3aa8c4503bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MC_LoginUser_LoginButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MC_LoginUser_LoginButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Log In&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6949bd45-d640-480d-81ca-4e1c8e9e4321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7f8ff9b-0f4f-4e5a-80f9-c4168398d4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MC$LoginUser$LoginButton</value>
      <webElementGuid>3910dac4-618c-4923-b065-0763c037fbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>0bc68cf3-058c-4013-8662-77f34da9a055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encrypt();WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$MC$LoginUser$LoginButton&quot;, &quot;&quot;, true, &quot;LoginUserValidationGroup&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>e6de0f25-0b2a-4fdc-8a85-0b64f032560e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MC_LoginUser_LoginButton</value>
      <webElementGuid>5ce1f339-6eb2-4703-bbdb-7647d110f706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-button</value>
      <webElementGuid>7dc39f61-13f7-4bc9-86f6-5aa2df2c0462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MC_LoginUser_LoginButton&quot;)</value>
      <webElementGuid>ad25204d-d901-449d-a8f8-a7bdf8affa7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MC_LoginUser_LoginButton']</value>
      <webElementGuid>b178c326-3bd4-4d68-ac2d-3a0fdb5535bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/div/input</value>
      <webElementGuid>028cb290-ab6b-467c-b1b0-750839a57fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>0bbf87f8-85e5-432b-b1ef-9db0dea98cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'ctl00$MC$LoginUser$LoginButton' and @id = 'MC_LoginUser_LoginButton']</value>
      <webElementGuid>ee3a9aa6-dc3d-4b34-956c-9669721a45f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
