<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Field is mandatory_ctl00MCLoginUserPassword</name>
   <tag></tag>
   <elementGuidId>b1e3cff6-e65d-4917-a6d7-cd83f783ae81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MC_LoginUser_Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MC_LoginUser_Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35e40fe9-c2bc-4249-8a1e-9033e0481908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MC$LoginUser$Password</value>
      <webElementGuid>d5ef2852-aad0-45fe-ac93-c4b43f078dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8a9fa79b-f145-45ea-b61d-9bae0954f4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MC_LoginUser_Password</value>
      <webElementGuid>15f8209b-8eed-4ec4-a76c-64635827502c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input</value>
      <webElementGuid>210c92d5-e3a3-43ab-9842-609ef3e438d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>9fba37a4-189a-479e-b419-a9d18de788b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>a553384a-a113-4805-ace7-b7e134375423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>06405e88-36ce-4e52-84b2-dd724e053c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>4065bd0b-eb5a-4507-8a64-814143410a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncut</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>9fdd7f95-4011-4776-86d2-b1917930124a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MC_LoginUser_Password&quot;)</value>
      <webElementGuid>82f13346-ca92-440c-8d20-8b5b8b418ed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MC_LoginUser_Password']</value>
      <webElementGuid>d434258f-a9a2-4b0c-9c82-3b67c2080c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/div/div[3]/div/input[2]</value>
      <webElementGuid>5b8ff13e-e6f3-42ee-848b-60563ddf9d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[2]</value>
      <webElementGuid>c83880bf-f34c-410a-bb8c-30b7b4601645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MC$LoginUser$Password' and @type = 'password' and @id = 'MC_LoginUser_Password' and @placeholder = 'Password']</value>
      <webElementGuid>401aef1e-9940-4069-82e7-0b9d51298d7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
